'use strict';

console.log(document.getElementById('start'));
//console.log(document.getElementById('cansel'));
console.log(document.getElementsByTagName('button')[0]);
console.log(document.getElementsByTagName('button')[1]);
console.log(document.querySelector('#deposit-check'));
console.log(document.querySelectorAll('.additional_income-item'));
console.log(document.getElementsByClassName('budget_month-value')[0]);
console.log(document.getElementsByClassName('budget_day-value')[0]);
console.log(document.getElementsByClassName('expenses_month-value')[0]);
console.log(document.getElementsByClassName('additional_income-value')[0]);
console.log(document.getElementsByClassName('additional_expenses-value')[0]);
console.log(document.getElementsByClassName('income_period-value')[0]);
console.log(document.getElementsByClassName('target_month-value')[0]);
console.log(document.querySelector('.period-select'));
console.log(document.querySelector('.target'));
console.log(document.querySelector('.additional_expenses'));
console.log(document.querySelector('.expenses'));
console.log(document.querySelector('.additional_income'));
console.log(document.querySelector('.income'));
console.log(document.querySelector('.salary'));
